version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build
hooks:
  BeforeInstall:
    - location: /initialize.sh
      runas: root

  ApplicationStart:
    - location: /start.sh
      runas: root
