version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - sudo chown -R ec2-user build
      - npm install
      - pwd
    run-as: root

artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"
